//generated from ./Settings.csv at 2022-01-24T13:02:16.828014
#ifndef USERSETTINGS_H
#define USERSETTINGS_H
#include "UserSettingsBase.h"
UserSettingsList userSettings={
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowS57Text"),UserSettingsEntry::TYPE_BOOL,1,wxT("Show text")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowS57ImportantTextOnly"),UserSettingsEntry::TYPE_BOOL,0,wxT("Important Text Only")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowLightDescription"),UserSettingsEntry::TYPE_BOOL,1,wxT("Light Descriptions")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bExtendLightSectors"),UserSettingsEntry::TYPE_BOOL,1,wxT("Extended Light Sectors")),
new UserSettingsEntryEnum(wxT("important"),wxT("/Settings/GlobalState"),wxT("nDisplayCategory"),UserSettingsEntry::TYPE_ENUM,79,wxT("Display Category"),{68,83,79,77},wxT("Base,Standard,All,User Standard")),
new UserSettingsEntryEnum(wxT("important"),wxT("/Settings/GlobalState"),wxT("nSymbolStyle"),UserSettingsEntry::TYPE_ENUM,82,wxT("Graphics Style"),{82,76},wxT("Paper Chart,Simplified")),
new UserSettingsEntryEnum(wxT("important"),wxT("/Settings/GlobalState"),wxT("nBoundaryStyle"),UserSettingsEntry::TYPE_ENUM,78,wxT("Boundaries"),{78,79},wxT("Plain,Symbolized")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowSoundg"),UserSettingsEntry::TYPE_BOOL,1,wxT("Show depths")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowMeta"),UserSettingsEntry::TYPE_BOOL,1,wxT("Chart Information Objects")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bUseSCAMIN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Reduced Detail at Small Scale")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowAtonText"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy/Light Labels")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bDeClutterText"),UserSettingsEntry::TYPE_BOOL,1,wxT("De-Cluttered Text")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/GlobalState"),wxT("bShowNationalText"),UserSettingsEntry::TYPE_BOOL,1,wxT("National text on chart")),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/GlobalState"),wxT("S52_MAR_SAFETY_CONTOUR"),UserSettingsEntry::TYPE_DEPTH,2.0,wxT("Safety Depth"),0,100),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/GlobalState"),wxT("S52_MAR_SHALLOW_CONTOUR"),UserSettingsEntry::TYPE_DEPTH,3.0,wxT("Shallow Depth"),0,100),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/GlobalState"),wxT("S52_MAR_DEEP_CONTOUR"),UserSettingsEntry::TYPE_DEPTH,5.0,wxT("Deep Depth"),0,100),
new UserSettingsEntryEnum(wxT("important"),wxT("/Settings/GlobalState"),wxT("S52_MAR_TWO_SHADES"),UserSettingsEntry::TYPE_ENUM,0,wxT("Colors"),{1,0},wxT("2Color,4 Color")),
new UserSettingsEntryEnum(wxT("important"),wxT("/Settings/GlobalState"),wxT("S52_DEPTH_UNIT_SHOW"),UserSettingsEntry::TYPE_ENUM,1,wxT("Depth"),{0,1,2},wxT("Feet, Meters, Fathoms")),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/AvNav"),wxT("chartFont"),UserSettingsEntry::TYPE_FLOAT,1,wxT("Text Font Size"),0.3,5),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/AvNav"),wxT("soundingsFont"),UserSettingsEntry::TYPE_FLOAT,1,wxT("Soundings Font Size"),0.3,5),
new UserSettingsEntryDouble(wxT("important"),wxT("/Settings/AvNav"),wxT("scale"),UserSettingsEntry::TYPE_FLOAT,2,wxT("Scale"),0.2,5),
new UserSettingsEntryInt(wxT("important"),wxT("/Settings/AvNav"),wxT("underZoom"),UserSettingsEntry::TYPE_INT,4,wxT("UnderZoom"),0,8),
new UserSettingsEntryInt(wxT("important"),wxT("/Settings/AvNav"),wxT("overZoom"),UserSettingsEntry::TYPE_INT,4,wxT("OverZoom"),1,8),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/AvNav"),wxT("showLights"),UserSettingsEntry::TYPE_BOOL,1,wxT("Show Lights")),
new UserSettingsEntryBool(wxT("important"),wxT("/Settings/AvNav"),wxT("showAnchorInfo"),UserSettingsEntry::TYPE_BOOL,1,wxT("Show Anchor Info")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizADMARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Administration area (Named)")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizAIRARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Airport / airfield")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizACHBRT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Anchor berth")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizACHPNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Anchor")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizACHARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Anchorage area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBCNCAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, cardinal")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBCNISD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, isolated danger")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBCNLAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, lateral")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBCNSAW"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, safe water")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBCNSPP"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, special purpose/general")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBERTHS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Berth")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBRIDGE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Bridge")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBUISGL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Building, single")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBUIREL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Building, religous")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBUAARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Built-up area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYCAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, cardinal")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYINB"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, installation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYISD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, isolated danger")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYLAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, lateral")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYSAW"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, safe water")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizBOYSPP"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, special purpose/general")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCBLARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cable area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCBLOHD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cable, overhead")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCBLSUB"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cable, submarine")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCANALS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Canal")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCANBNK"),UserSettingsEntry::TYPE_BOOL,1,wxT("Canal bank")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCTSARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cargo transshipment area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCAUSWY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Causeway")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCTNARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Caution area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCHNWIR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Chain/Wire")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCHKPNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Checkpoint")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCGUSTA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Coastguard station")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCOALNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Coastline")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCONZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Contiguous zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCOSARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Continental shelf area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCTRPNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Control point")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCONVYR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Conveyor")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCRANES"),UserSettingsEntry::TYPE_BOOL,1,wxT("Crane")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCURENT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Current - non - gravitational")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizCUSZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Custom zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDAMCON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dam")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDAYMAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Daymark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDWRTCL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Deep water route centerline")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDWRTPT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Deep water route part")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDEPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Depth area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDEPCNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Depth contour")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDISMAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Distance mark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDOCARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dock area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDRGARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dredged area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDRYDOC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dry dock")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDMPGRD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dumping ground")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizDYKCON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Dyke")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizEXEZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Exclusive Economic Zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFAIRWY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fairway")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFNCLNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fence/wall")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFERYRT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Ferry route")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFSHZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fishery zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFSHFAC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fishing facility")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFSHGRD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fishing ground")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFLODOC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Floating dock")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFOGSIG"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fog signal")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFORSTC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Fortified structure")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizFRPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Free port area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizGATCON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Gate")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizGRIDRN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Gridiron")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizHRBARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Harbour area (administrative)")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizHRBFAC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Harbour facility")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizHULKES"),UserSettingsEntry::TYPE_BOOL,1,wxT("Hulk")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizICEARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Ice area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizICNARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Incineration area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizISTZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Inshore traffic zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLAKARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lake")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLAKSHR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lake shore")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLNDARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Land area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLNDELV"),UserSettingsEntry::TYPE_BOOL,1,wxT("Land elevation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLNDRGN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Land region")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLNDMRK"),UserSettingsEntry::TYPE_BOOL,1,wxT("Landmark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLIGHTS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Light")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz_extgn"),UserSettingsEntry::TYPE_BOOL,1,wxT("Light, extinguished")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLITFLT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Light float")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLITVES"),UserSettingsEntry::TYPE_BOOL,1,wxT("Light vessel")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLOCMAG"),UserSettingsEntry::TYPE_BOOL,1,wxT("Local magnetic anomaly")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLOKBSN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lock basin")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizLOGPON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Log pond")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizMAGVAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Magnetic variation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizMARCUL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Marine farm/culture")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizMIPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Military practice area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizMONUMT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Monument")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizMORFAC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Mooring/warping facility")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizNAVLNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Navigation line")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizOBSTRN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Obstruction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizOFSPLF"),UserSettingsEntry::TYPE_BOOL,1,wxT("Offshore platform")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizOSPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Offshore production area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizOILBAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Oil barrier")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPILPNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pile")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPILBOP"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pilot boarding place")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPIPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pipeline area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPIPOHD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pipeline, overhead")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPIPSOL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pipeline, submarine/on land")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPONTON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pontoon")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPRCARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Precautionary area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPRDARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Production / storage area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizPYLONS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pylon/bridge support")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRADLNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radar line")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRADRNG"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radar range")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRADRFL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radar reflector")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRADSTA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radar station")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRTPBCN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radar transponder beacon")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRDOCAL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radio calling-in point")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRDOSTA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radio station")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRAILWY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Railway")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRAPIDS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Rapids")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRCRTCL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Recommended route centerline")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRECTRC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Recommended track")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRCTLPT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Recommended Traffic Lane Part")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRSCSTA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Rescue station")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRESARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Restricted area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRETRFL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Retro-reflector")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRIVERS"),UserSettingsEntry::TYPE_BOOL,1,wxT("River")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRIVBNK"),UserSettingsEntry::TYPE_BOOL,1,wxT("River bank")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizROADWY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Road")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRUNWAY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Runway")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSNDWAV"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sand waves")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSEAARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sea area / named water area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSPLARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sea-plane landing area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSBDARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Seabed area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSLCONS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Shoreline Construction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSISTAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Signal station, traffic")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSISTAW"),UserSettingsEntry::TYPE_BOOL,1,wxT("Signal station, warning")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSILTNK"),UserSettingsEntry::TYPE_BOOL,1,wxT("Silo / tank")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSLOTOP"),UserSettingsEntry::TYPE_BOOL,1,wxT("Slope topline")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSLOGRD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sloping ground")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSMCFAC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Small craft facility")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSOUNDG"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sounding")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSPRING"),UserSettingsEntry::TYPE_BOOL,1,wxT("Spring")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSQUARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Square")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSTSLNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Straight territorial sea baseline")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSUBTLN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Submarine transit lane")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizSWPARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Swept Area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTESARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Territorial sea area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz_texto"),UserSettingsEntry::TYPE_BOOL,1,wxT("Text")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTS_PRH"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream - harmonic prediction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTS_PNH"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream - non-harmonic prediction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTS_PAD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream panel data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTS_TIS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream - time series")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizT_HMON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tide - harmonic prediction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizT_NHMN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tide - non-harmonic prediction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizT_TIMS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream - time series")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTIDEWY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tideway")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTOPMAR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Topmark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTOWERS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tower")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSELNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Line")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSSBND"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Scheme  Boundary")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSSCRS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Scheme Crossing")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSSLPT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Scheme  Lane part")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSSRON"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Scheme  Roundabout")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTSEZNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Separation Zone")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTUNNEL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tunnel")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTWRTPT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Two-way route  part")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizUWTROC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Underwater rock / awash rock")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizUNSARE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Unsurveyed area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizVEGATN"),UserSettingsEntry::TYPE_BOOL,1,wxT("Vegetation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizWATTUR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Water turbulence")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizWATFAL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Waterfall")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizWEDKLP"),UserSettingsEntry::TYPE_BOOL,1,wxT("Weed/Kelp")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizWRECKS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Wreck")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizZEMCNT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Zero meter contour")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTS_FEB"),UserSettingsEntry::TYPE_BOOL,1,wxT("Tidal stream - flood/ebb")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizNEWOBJ"),UserSettingsEntry::TYPE_BOOL,1,wxT("New Object")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_ACCY"),UserSettingsEntry::TYPE_BOOL,1,wxT("Accuracy of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_CSCL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Compilation scale of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_COVR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Coverage")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_HDAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Horizontal datum of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_HOPA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Horizontal datum shift parameters")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_NPUB"),UserSettingsEntry::TYPE_BOOL,1,wxT("Nautical publication information")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_NSYS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Navigational system of marks")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_PROD"),UserSettingsEntry::TYPE_BOOL,1,wxT("Production information")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_QUAL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Quality of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_SDAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sounding datum")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_SREL"),UserSettingsEntry::TYPE_BOOL,1,wxT("Survey reliability")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_UNIT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Units of measurement of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizM_VDAT"),UserSettingsEntry::TYPE_BOOL,1,wxT("Vertical datum of data")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizC_AGGR"),UserSettingsEntry::TYPE_BOOL,1,wxT("Aggregation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizC_ASSO"),UserSettingsEntry::TYPE_BOOL,1,wxT("Association")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizC_STAC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Stacked on/stacked under")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz$AREAS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cartographic area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz$LINES"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cartographic line")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz$CSYMB"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cartographic symbol")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz$COMPS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Compass")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viz$TEXTS"),UserSettingsEntry::TYPE_BOOL,1,wxT("Text")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizachbrt"),UserSettingsEntry::TYPE_BOOL,1,wxT("Anchor berth")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizachare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Anchorage area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizcanbnk"),UserSettingsEntry::TYPE_BOOL,1,wxT("Canal bank")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizdepare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Depth area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizdismar"),UserSettingsEntry::TYPE_BOOL,1,wxT("distance mark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizresare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Restricted area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizrivbnk"),UserSettingsEntry::TYPE_BOOL,1,wxT("River bank")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizsistat"),UserSettingsEntry::TYPE_BOOL,1,wxT("Signal station, traffic")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizsistaw"),UserSettingsEntry::TYPE_BOOL,1,wxT("Signal station, warning")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viztopmar"),UserSettingsEntry::TYPE_BOOL,1,wxT("Top Mark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizberths"),UserSettingsEntry::TYPE_BOOL,1,wxT("Berth")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizbridge"),UserSettingsEntry::TYPE_BOOL,1,wxT("Bridge")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizcblohd"),UserSettingsEntry::TYPE_BOOL,1,wxT("Cable, overhead")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizferyrt"),UserSettingsEntry::TYPE_BOOL,1,wxT("Ferry route")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizhrbare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Harbour area (administrative)")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizhrbfac"),UserSettingsEntry::TYPE_BOOL,1,wxT("Harbour facility")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizlokbsn"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lock basin")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizrdocal"),UserSettingsEntry::TYPE_BOOL,1,wxT("Radio calling-in point")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizm_nsys"),UserSettingsEntry::TYPE_BOOL,1,wxT("Navigational system of marks")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizcurent"),UserSettingsEntry::TYPE_BOOL,1,wxT("Current, non-gravitational")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizhulkes"),UserSettingsEntry::TYPE_BOOL,1,wxT("Hulk")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizponton"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pontoon")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizm_sdat"),UserSettingsEntry::TYPE_BOOL,1,wxT("Sounding datum")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizm_vdat"),UserSettingsEntry::TYPE_BOOL,1,wxT("Vertical datum")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizpipohd"),UserSettingsEntry::TYPE_BOOL,1,wxT("Pipeline, overhead")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizflodoc"),UserSettingsEntry::TYPE_BOOL,1,wxT("Floating dock")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizchkpnt"),UserSettingsEntry::TYPE_BOOL,1,wxT("Checkpoint")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizbcnlat"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon, lateral")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizboylat"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy, lateral")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizcranes"),UserSettingsEntry::TYPE_BOOL,1,wxT("Crane")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizgatcon"),UserSettingsEntry::TYPE_BOOL,1,wxT("Gate")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizslcons"),UserSettingsEntry::TYPE_BOOL,1,wxT("Shoreline Construction")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizuwtroc"),UserSettingsEntry::TYPE_BOOL,1,wxT("Underwater rock / awash rock")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizconvyr"),UserSettingsEntry::TYPE_BOOL,1,wxT("Conveyor")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viznotmrk"),UserSettingsEntry::TYPE_BOOL,1,wxT("Notice mark")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizwtwaxs"),UserSettingsEntry::TYPE_BOOL,1,wxT("waterway axis")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizwtwprf"),UserSettingsEntry::TYPE_BOOL,1,wxT("waterway profile")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizbrgare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Bridge area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizbunsta"),UserSettingsEntry::TYPE_BOOL,1,wxT("Bunker station")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizcomare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Communication area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizhrbbsn"),UserSettingsEntry::TYPE_BOOL,1,wxT("Harbour basin")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizlokare"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lock area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizlkbspt"),UserSettingsEntry::TYPE_BOOL,1,wxT("Lock basin part")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizprtare"),UserSettingsEntry::TYPE_BOOL,1,wxT("port area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizbcnwtw"),UserSettingsEntry::TYPE_BOOL,1,wxT("Beacon water-way")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizboywtw"),UserSettingsEntry::TYPE_BOOL,1,wxT("Buoy water-way")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizrefdmp"),UserSettingsEntry::TYPE_BOOL,1,wxT("refuse dump")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizrtplpt"),UserSettingsEntry::TYPE_BOOL,1,wxT("Route planning point")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viztermnl"),UserSettingsEntry::TYPE_BOOL,1,wxT("terminal")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viztrnbsn"),UserSettingsEntry::TYPE_BOOL,1,wxT("turning basin")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizwtware"),UserSettingsEntry::TYPE_BOOL,1,wxT("Waterway area")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizwtwgag"),UserSettingsEntry::TYPE_BOOL,1,wxT("Waterway gauge")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("viztisdge"),UserSettingsEntry::TYPE_BOOL,1,wxT("Time Schedule - in general")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizvehtrf"),UserSettingsEntry::TYPE_BOOL,1,wxT("Vehicle transfer")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizexcnst"),UserSettingsEntry::TYPE_BOOL,1,wxT("Exceptional navigation structure")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizlg_sdm"),UserSettingsEntry::TYPE_BOOL,1,wxT("Maximum permitted ship dimensions")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizlg_vsp"),UserSettingsEntry::TYPE_BOOL,1,wxT("Maximum permitted vessel speed")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizANNOTA"),UserSettingsEntry::TYPE_BOOL,1,wxT("Annotation")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizRESTRC"),UserSettingsEntry::TYPE_BOOL,1,wxT("Generic Boundary")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizTRFLNE"),UserSettingsEntry::TYPE_BOOL,1,wxT("Traffic Line")),
new UserSettingsEntryBool(wxT("detail"),wxT("/Settings/ObjectFilter"),wxT("vizGENNAV"),UserSettingsEntry::TYPE_BOOL,1,wxT("Generic NavAid"))
};
#endif
